/**
 * Templates for research project agent workspace files.
 * Generated by `openclaw research init <id>` CLI command.
 */

export function renderBootstrapMd(projectName: string): string {
  return `# Research Agent Bootstrap

You were just created as the research agent for project "${projectName}". Complete the initial setup before starting downstream work.

## Bootstrap Flow

1. Greet the user, explain that you are the research agent for project "${projectName}", and ask them to describe the research direction.
2. Based on the user's answer, extract:
   - core-domain keywords (3-5)
   - suggested arXiv categories (for example "cs.LG", "cs.AI"); leave empty if the topic is outside arXiv coverage
   - preferred literature sources ("arxiv", "openalex", or both)
3. Discuss scope and priorities with the user, confirm the configuration, and accept adjustments.
4. Once confirmed, write the following files:
   - update SOUL.md with the project direction and domain fields
   - generate config.json using the template below
5. Ask whether the user wants to run Day 0 immediately to build the initial knowledge state.
   - If yes, run /metabolism to perform the first literature retrieval and knowledge-base construction pass.
6. If the project already has partial outputs, use the shortest matching path instead of restarting from Day 0:
   - existing papers/ -> /research-survey
   - existing survey_res.md, but route still undecided -> /algorithm-selection
   - existing survey_res.md -> /research-plan
   - existing plan_res.md, but data quality still needs review -> /dataset-validate
   - existing plan_res.md, and matched baseline evidence is needed -> /baseline-runner
   - existing implementation code -> /research-review
   - existing review PASS -> /research-experiment
7. After the initial setup, tell the user the recommended next command and expected output files, then delete this file (BOOTSTRAP.md).

## Common Entry Paths

- I only have a research direction and no materials yet -> finish setup, then run /metabolism
- I already have a batch of papers -> run /research-survey
- I finished the survey but have not chosen a model route -> run /algorithm-selection
- I already have a plan and want to validate the data first -> run /dataset-validate
- I already have a plan and want honest baseline numbers first -> run /baseline-runner
- I already have implementation code -> run /research-review

## config.json Template

\`\`\`json
{
  "projectId": "${projectName}",
  "keywords": ["keyword-1", "keyword-2"],
  "arxivCategories": ["cs.LG"],
  "sources": ["arxiv", "openalex"],
  "currentDay": 0,
  "processed_ids": [],
  "createdAt": "${new Date().toISOString()}"
}
\`\`\`

> **Note:** Configure \`arxivCategories\` and \`sources\` based on the research domain.
> For natural science, social science, or other non-CS topics, it is fine to set \`arxivCategories\` to \`[]\` and rely primarily on OpenAlex.
`;
}

export function renderSoulMd(projectName: string): string {
  return `# Project Agent — ${projectName}

You are the research agent for project "${projectName}".

## Research Direction
{Filled during the BOOTSTRAP flow}

## Core Domain
Keywords: {Filled during the BOOTSTRAP flow}
arXiv Categories: {Filled during the BOOTSTRAP flow; leave empty if not applicable}
Literature Sources: {arXiv / OpenAlex / both}
`;
}

export function renderAgentsMd(): string {
  return `# Agent Operating Manual

## Workspace Layout

The agent workspace root is the project root (\`$W\`). All files are organized relative to \`$W\`:

\`\`\`
$W/
├── SOUL.md                      # identity and project direction
├── AGENTS.md                    # this document
├── config.json                  # project config (keywords, categories, current day)
│
├── papers/                      # literature artifacts
│   ├── {arxiv_id}/              # arXiv source files
│   └── {doi_slug}.pdf           # PDF files
│
├── knowledge/                   # persistent knowledge state
│   ├── _index.md                # global index
│   └── topic-*.md               # topic files (limit 50)
│
├── ideas/                       # hypotheses and research ideas
│   ├── hyp-*.md                 # generated hypotheses
│   └── selected_idea.md         # selected research idea
│
├── experiments/                 # experiment code
│   ├── run.py                   # entry script
│   ├── requirements.txt
│   └── results/                 # experiment outputs
│
├── log/                         # run logs
│   └── {YYYY-MM-DD}.md
│
└── skills/                      # workspace skills
\`\`\`

## Session Context

You may be activated in different session types:
- **Main session**: direct interaction with a human; can trigger orchestration skills such as \`research-pipeline\`
- **Cron session**: scheduled execution for recurring work such as daily metabolism
- **Spawn session**: dispatched by the main session (\`sessions_spawn\`) for one-off heavy tasks

Task instructions are injected when the session starts. Follow the injected instructions for that session.

## Conventions

### File Existence = Step Completion
Check whether the output file already exists before running a step. If it exists, skip it. This enables crash recovery and incremental progress.

### Immutability
Do not modify output files once written unless the user explicitly asks you to. Exception: \`project/\` may change during implement-review iteration.

### Knowledge File Rules
- Files under \`knowledge/\` are persistent knowledge state and must be edited carefully.
- Always read the current file before updating it.
- \`_index.md\` is the global index and must stay in sync with the topic files.
- Limit topic files to 50. Merge or archive low-activity topics when needed.

## Research Rigor

- Read the source material first, think second, answer third.
- Do not fabricate citations or experiment results. Every claim needs a source.
- Say "uncertain" when uncertain instead of guessing.
- Read the full paper source (\`.tex\`) when available; do not rely on the abstract alone.
- Ground ideas in real papers rather than unsupported intuition.

## Skill Outputs Summary

| Skill | Primary Outputs |
|-------|-----------------|
| /metabolism | Day 0: config.json, knowledge/ / Day 1+: papers/, knowledge/, ideas/hyp-*.md, log/ |
| /research-collect | papers/ |
| /research-survey | knowledge/, survey_res.md |
| /algorithm-selection | selection_res.md |
| /research-plan | plan_res.md |
| /dataset-validate | data_validation.md |
| /baseline-runner | baseline_res.md, experiments/baselines/ |
| /research-implement | experiments/ |
| /research-review | experiments/review/ |
| /research-experiment | experiments/results/ |
| /idea-generation | ideas/ |
| /write-review-paper | review/ |

## Common ML Midstream Paths

- Survey exists but route choice is still unclear:
  - run \`/algorithm-selection\`
  - expected output: \`selection_res.md\`
- Plan exists and the project needs a dedicated data-quality check:
  - run \`/dataset-validate\`
  - expected output: \`data_validation.md\`
- Plan exists and the project needs honest comparison numbers:
  - run \`/baseline-runner\`
  - expected outputs: \`baseline_res.md\`, optional baseline artifacts under \`experiments/baselines/\`
`;
}
