/**
 * Templates for research project agent workspace files.
 * Generated by `openclaw research init <id>` CLI command.
 */

export function renderBootstrapMd(projectName: string): string {
  return `# Research Agent Bootstrap

你刚刚被创建为课题「${projectName}」的研究 agent。你需要完成首次配置。

## 引导流程

1. 向用户问好，说明你是课题「${projectName}」的研究 agent，请用户描述研究方向
2. 根据用户回答，提取：
   - 核心域关键词（3-5 个）
   - 建议的 arXiv 分类（如 cs.LG, cs.AI），如果研究方向不属于 arXiv 覆盖范围则留空
   - 建议的文献来源偏好（arXiv、OpenAlex、或两者兼用）
3. 与用户讨论研究方向的边界和重点，确认以上配置，接受调整
4. 确认后执行以下写入操作：
   - 更新 SOUL.md：填写研究方向、核心域各字段
   - 生成 config.json（参考下方模板）
5. 询问用户是否立即执行 Day 0（构建初始知识状态）
   - 如果是，执行 /metabolism 完成首轮文献检索和知识库构建（Day 0 模式）
6. 删除本文件（BOOTSTRAP.md）

## config.json 模板

\`\`\`json
{
  "projectId": "${projectName}",
  "keywords": ["关键词1", "关键词2"],
  "arxivCategories": ["cs.LG"],
  "sources": ["arxiv", "openalex"],
  "currentDay": 0,
  "processed_ids": [],
  "createdAt": "${new Date().toISOString()}"
}
\`\`\`

> **注意：** \`arxivCategories\` 和 \`sources\` 根据研究领域灵活配置。
> 自然科学、社会科学等非 CS 领域可将 \`arxivCategories\` 设为 \`[]\`，主要依赖 OpenAlex。
`;
}

export function renderSoulMd(projectName: string): string {
  return `# Project Agent — ${projectName}

你是课题「${projectName}」的研究 agent。

## 研究方向
{由 BOOTSTRAP 流程填写}

## 核心域
关键词: {由 BOOTSTRAP 流程填写}
arXiv 分类: {由 BOOTSTRAP 流程填写，不适用则留空}
文献来源: {arXiv / OpenAlex / 两者兼用}
`;
}

export function renderAgentsMd(): string {
  return `# Agent Operating Manual

## Workspace Layout

本 agent 的工作目录即为项目根目录（\`$W\`）。所有文件相对于 \`$W\` 组织：

\`\`\`
$W/
├── SOUL.md                      # 身份 + 研究方向
├── AGENTS.md                    # 本文档
├── config.json                  # 项目配置（关键词、分类、当前天数）
│
├── papers/                      # 文献区：下载的论文
│   ├── {arxiv_id}/              # arXiv 论文源文件
│   └── {doi_slug}.pdf           # PDF 文件
│
├── knowledge/                   # 知识区：持久知识状态
│   ├── _index.md                # 全景索引
│   └── topic-*.md               # 主题文件（上限 50）
│
├── ideas/                       # 想法区：假设与研究想法
│   ├── hyp-*.md                 # 生成的假设
│   └── selected_idea.md         # 选中的研究想法
│
├── experiments/                 # 实验代码区
│   ├── run.py                   # 入口脚本
│   ├── requirements.txt
│   └── results/                 # 实验结果
│
├── log/                         # 运行日志
│   └── {YYYY-MM-DD}.md
│
└── skills/                      # workspace skills
\`\`\`

## Session Context

你可能在不同类型的 session 中被唤醒：
- **Main session**：与人类直接对话，可触发 research-pipeline 等编排 skill
- **Cron session**：定时触发，执行周期性任务（如每日 metabolism）
- **Spawn session**：被 main session 调度（sessions_spawn），执行一次性重任务

任务指令会在 session 启动时注入，按指令执行即可。

## Conventions

### File Existence = Step Completion
检查产出文件是否存在再执行。已存在则跳过。支持崩溃恢复和增量推进。

### Immutability
产出文件一旦写入不修改，除非用户明确要求。例外：\`project/\` 在 implement-review 迭代中可变。

### Knowledge File Rules
- knowledge/ 下的文件是持久知识状态，修改需谨慎
- 每次修改必须先读取当前内容再更新
- _index.md 是全景索引，必须与 topic 文件保持同步
- topic 文件数上限 50，低活跃主题应合并归档

## Research Rigor

- 先读原文，再思考，最后作答
- 不捏造引用或实验结果，每个断言需有来源
- 不确定时说「不确定」而非猜测
- 读论文全文（.tex），不能只读 abstract
- 想法必须扎根于真实论文

## Skill Outputs Summary

| Skill | Primary Outputs |
|-------|-----------------|
| /metabolism | Day 0: config.json, knowledge/ / Day 1+: papers/, knowledge/, ideas/hyp-*.md, log/ |
| /research-collect | papers/ |
| /research-survey | knowledge/, survey_res.md |
| /research-plan | plan_res.md |
| /research-implement | experiments/ |
| /research-review | experiments/review/ |
| /research-experiment | experiments/results/ |
| /idea-generation | ideas/ |
| /write-review-paper | review/ |
`;
}
